apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-openshift
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-openshift
  template:
    metadata:
      labels:
        app: springboot-openshift
    spec:
      containers:
      - name: springboot-openshift-container
        image: iamshyam1911/springboot-cse-openshift:latest
        ports:
        - containerPort: 8085