apiVersion: v1
kind: Service
metadata:
  name: springboot-openshift-service
spec:
  selector:
    app: springboot-openshift
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP